import Mathlib.Algebra.CharP.Defs
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.Analysis.Normed.Ring.Lemmas

/-!
This self-contained module is the auditable statement layer.

The source notes below compare its declarations with Baker and Norine's paper. Short displayed
formulae are quoted from the paper; the surrounding prose is a source-faithful paraphrase.
-/

universe u

open Multiset Finset

/--
The paper works throughout with finite, unweighted, loopless multigraphs and assumes that they
are connected. Here finiteness, the absence of loops, and nonemptiness are bundled into the graph
structure, while connectedness is an explicit hypothesis on the propositions below.
-/
structure CFGraph where
  V : Type u
  [instDecidableEq : DecidableEq V]
  [instFintype : Fintype V]
  [instNonempty : Nonempty V]
  (edges : Multiset (V × V))
  (loopless : ∀ v, (v, v) ∉ edges)

attribute [instance] CFGraph.instDecidableEq CFGraph.instFintype CFGraph.instNonempty

/--
The multiplicity of the edge between `v` and `w`. This is the corresponding off-diagonal entry of
the paper's adjacency matrix; an edge may be stored in either orientation in `G.edges`.
-/
def num_edges (G : CFGraph) (v w : G.V) : ℕ :=
  Multiset.card (G.edges.filter (λ e => e = (v, w) ∨ e = (w, v)))

/--
Connectedness in cut form: every partition into two nonempty vertex sets has an edge crossing it.
The paper assumes connectedness globally and gives this cut characterization in its discussion of
edge-connectivity.
-/
def graph_connected (G : CFGraph) : Prop :=
  ∀ S : Finset G.V, (∃ (v w : G.V), v ∈ S ∧ w ∉ S) →
    (∃ v ∈ S, ∃ w ∉ S, num_edges G v w > 0)

/--
The graph genus (its cyclomatic number or first Betti number).

> \(g = |E(G)| - |V(G)| + 1\).
-/
def genus (G : CFGraph) : ℤ :=
  Multiset.card G.edges - Fintype.card G.V + 1

/--
The degree (valency) of `v`, counting incident edges with multiplicity. It is the diagonal entry of
the degree matrix used to define the paper's graph Laplacian.
-/
def vertex_degree (G : CFGraph) (v : G.V) : ℤ :=
  ∑ u : G.V, (num_edges G v u : ℤ)

/--
A divisor is an integral coefficient at every vertex. This function model is canonically the free
abelian group on the finite vertex set used in the paper.
-/
abbrev CFDiv (G : CFGraph) := G.V → ℤ

/--
The change produced by firing `v`: subtract its valency there and add the appropriate edge
multiplicity at every neighboring vertex. This is the negative of the paper's
`Δ(χ_{v})`; taking all integer combinations therefore gives the same subgroup as the image of its
Laplacian.
-/
def firing_vector (G : CFGraph) (v : G.V) : CFDiv G :=
  λ w => if w = v then -vertex_degree G v else num_edges G v w

/--
The subgroup generated by firing moves. It agrees with the paper's subgroup of principal divisors,
which is the image of the group of integer-valued vertex functions under the graph Laplacian.
-/
def principal_divisors (G : CFGraph) : AddSubgroup (CFDiv G) :=
  AddSubgroup.closure (Set.range (firing_vector G))

def linear_equiv (G : CFGraph) (D D' : CFDiv G) : Prop :=
  D' - D ∈ principal_divisors G

def effective {G : CFGraph} (D : CFDiv G) : Prop :=
  ∀ v : G.V, D v ≥ 0

/--
The effective divisors, packaged as an additive submonoid. 
-/
def Eff (G : CFGraph) : AddSubmonoid (CFDiv G) :=
  { carrier := {D : CFDiv G | effective D},
    zero_mem' := by
      simp only [effective, ge_iff_le, Set.mem_ofPred_eq, Pi.zero_apply, Std.le_refl, implies_true]
    add_mem' := by
      intro D₁ D₂ h_eff1 h_eff2 v
      exact add_nonneg (h_eff1 v) (h_eff2 v) }

/--
The divisor `D` is linearly equivalent to an effective divisor. Equivalently, its associated linear
system is nonempty, or the paper's chip-firing game starting at `D` has a winning strategy.
-/
def winnable (G : CFGraph) (D : CFDiv G) : Prop :=
  ∃ D' ∈ Eff G, linear_equiv G D D'

/--
The degree homomorphism sums the coefficients of a divisor.

> \(\deg(D) = \sum_{v \in V(G)} D(v)\).
-/
def deg {G : CFGraph} : CFDiv G →+ ℤ := {
  toFun := λ D => ∑ v, D v,
  map_zero' := by
    simp only [Pi.zero_apply, sum_const_zero],
  map_add' := by
    intro D₁ D₂
    simp only [Pi.add_apply, sum_add_distrib],
}

/--
The effective divisors of degree `k`, corresponding to the paper's `Div₊^k(G)`.
-/
def eff_of_degree (G : CFGraph) (k : ℤ) : Set (CFDiv G) :=
  {E | effective E ∧ deg E = k}

/--
The lower-bound relation for divisor rank: subtracting any effective divisor of degree `k` leaves
a divisor whose linear system is nonempty. For nonnegative `k`, this is precisely the paper's
criterion for `r(D) ≥ k`; extending it to every integer makes the rank-minus-one case uniform.
-/
def rank_geq (G : CFGraph) (D : CFDiv G) (k : ℤ) : Prop :=
  ∀ E ∈ eff_of_degree G k, winnable G (D-E)

/--
A relational presentation of the paper's integer-valued rank: the lower-bound criterion holds at
`r` and fails at `r + 1`. In particular, rank `-1` says that `D` is not winnable, matching the
paper's separate `|D| = ∅` clause.
-/
def rank_eq (G : CFGraph) (D : CFDiv G) (r : ℤ) : Prop :=
  rank_geq G D r ∧ ¬(rank_geq G D (r+1))

/--
The canonical divisor has coefficient `deg(v) - 2` at each vertex.

> \(K = \sum_{v \in V(G)} (\deg(v)-2)(v)\).

[Baker--Norine (2007)](https://doi.org/10.1016/j.aim.2007.04.012), §1.5.
-/
def canonical_divisor (G : CFGraph) : CFDiv G :=
  λ v => (vertex_degree G v) - 2

namespace Propositions

/--
Riemann–Roch for graphs.

> \(r(D) - r(K-D) = \deg(D) + 1 - g\).

This is Theorem 1.12 of
[Baker--Norine (2007)](https://doi.org/10.1016/j.aim.2007.04.012). The two `rank_eq`
hypotheses expose the values of the relational rank in place of applying a rank function.
-/
theorem riemann_roch {G : CFGraph} (h_conn : graph_connected G) (D : CFDiv G) :
    ∀ r rdual : ℤ, rank_eq G D r → rank_eq G (canonical_divisor G - D) rdual →
      r - rdual = deg D + 1 - genus G := by
  sorry

/--
Clifford's theorem for graphs.

> \(r(D) \leq \frac{1}{2}\deg(D)\).

This is Corollary 3.5 of
[Baker--Norine (2007)](https://doi.org/10.1016/j.aim.2007.04.012). The source assumes an effective
special representative. Here `0 ≤ r` and `0 ≤ rdual` say instead that both relevant divisor
classes contain effective representatives, which is the equivalent linear-equivalence-invariant
form used by this statement layer.
-/
theorem clifford {G : CFGraph} (h_conn : graph_connected G) (D : CFDiv G) :
    ∀ r rdual : ℤ, rank_eq G D r → rank_eq G (canonical_divisor G - D) rdual →
      0 ≤ r → 0 ≤ rdual → (r : ℚ) ≤ (deg D : ℚ) / 2 := by
  sorry

end Propositions
