name: Lean4 Correctness Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1

      
